### ISSUE TITLE
SwaggerValidationError 'states,words' is not of type 'array'

### ISSUE THREAD

**Issue by paulkarpenko** [HendrikStrobelt/LSTMVis#58]
Upon running `python lstm_server.py -dir data` I get the error below. I'm running Python 2.7.15 in a virtualenv and I haven't altered any files or directories save for creating `/data` and downloading the two corpus packs. Any help would be greatly appreciated, thank you :)

```Traceback (most recent call last):
  File "lstm_server.py", line 169, in <module>
    app.add_api('lstm_server.yaml')
  File "/Users/pkarpenko/Documents/Dev/python/LSTMVis/venv/lib/python2.7/site-packages/connexion/app.py", line 168, in add_api
    validator_map=self.validator_map)
  File "/Users/pkarpenko/Documents/Dev/python/LSTMVis/venv/lib/python2.7/site-packages/connexion/api.py", line 108, in __init__
    validate_spec(spec)
  File "/Users/pkarpenko/Documents/Dev/python/LSTMVis/venv/lib/python2.7/site-packages/swagger_spec_validator/validator20.py", line 97, in validate_spec
    validate_apis(apis, bound_deref)
  File "/Users/pkarpenko/Documents/Dev/python/LSTMVis/venv/lib/python2.7/site-packages/swagger_spec_validator/validator20.py", line 310, in validate_apis
    idx=idx,
  File "/Users/pkarpenko/Documents/Dev/python/LSTMVis/venv/lib/python2.7/site-packages/swagger_spec_validator/validator20.py", line 243, in validate_parameter
    validate_default_in_parameter(param, deref)
  File "/Users/pkarpenko/Documents/Dev/python/LSTMVis/venv/lib/python2.7/site-packages/swagger_spec_validator/validator20.py", line 172, in validate_default_in_parameter
    deref=deref,
  File "/Users/pkarpenko/Documents/Dev/python/LSTMVis/venv/lib/python2.7/site-packages/swagger_spec_validator/common.py", line 29, in wrapper
    sys.exc_info()[2])
  File "/Users/pkarpenko/Documents/Dev/python/LSTMVis/venv/lib/python2.7/site-packages/swagger_spec_validator/common.py", line 24, in wrapper
    return method(*args, **kwargs)
  File "/Users/pkarpenko/Documents/Dev/python/LSTMVis/venv/lib/python2.7/site-packages/swagger_spec_validator/validator20.py", line 155, in validate_value_type
    validate_schema_value(schema=deref(schema), value=value, swagger_resolver=swagger_resolver)
  File "/Users/pkarpenko/Documents/Dev/python/LSTMVis/venv/lib/python2.7/site-packages/swagger_spec_validator/ref_validators.py", line 101, in validate_schema_value
    create_dereffing_validator(swagger_resolver)(schema, resolver=swagger_resolver).validate(value)
  File "/Users/pkarpenko/Documents/Dev/python/LSTMVis/venv/lib/python2.7/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
swagger_spec_validator.common.SwaggerValidationError: ('\'states,words\' is not of type \'array\'\n\nFailed validating \'type\' in schema:\n    {\'collectionFormat\': \'csv\',\n     \'default\': \'states,words\',\n     \'description\': "list of required data dimensions, like state values (\'states\'), token values (\'words\'),\\n  or meta information (\'meta_XYZ\')\\n",\n     \'in\': \'query\',\n     \'items\': {\'type\': \'string\'},\n     \'name\': \'dims\',\n     \'required\': False,\n     \'type\': \'array\'}\n\nOn instance:\n    \'states,words\'', <ValidationError: "'states,words' is not of type 'array'">)

**Comment by HendrikStrobelt** [comment]
I will look into it.. might be a some version thing.. could you send me your pip freeze ?

**Comment by paulkarpenko** [comment]
Sure thing, and thank you!

`pip freeze`:
```appnope==0.1.0
backports-abc==0.5
backports.functools-lru-cache==1.5
backports.shutil-get-terminal-size==1.0.0
certifi==2018.4.16
chardet==3.0.4
click==6.7
clickclick==1.2.2
connexion==1.1.5
cycler==0.10.0
cymem==1.31.2
cytoolz==0.8.2
decorator==4.3.0
dill==0.2.7.1
enum34==1.1.6
Flask==0.12.1
functools32==3.2.3.post2
futures==3.2.0
h5py==2.7.0
idna==2.7
ipykernel==4.8.2
ipython==5.7.0
ipython-genutils==0.2.0
itsdangerous==0.24
Jinja2==2.10
jsonschema==2.6.0
jupyter-client==5.2.3
jupyter-core==4.4.0
kiwisolver==1.0.1
MarkupSafe==1.0
matplotlib==2.2.2
msgpack-numpy==0.4.1
msgpack-python==0.5.6
murmurhash==0.28.0
numpy==1.12.1
pathlib==1.0.1
pathlib2==2.3.2
pexpect==4.6.0
pickleshare==0.7.4
plac==0.9.6
preshed==1.0.0
prompt-toolkit==1.0.15
ptyprocess==0.5.2
Pygments==2.2.0
pyparsing==2.2.0
python-dateutil==2.7.3
pytz==2018.4
PyYAML==3.12
pyzmq==17.0.0
regex==2017.4.5
requests==2.19.0
scandir==1.7
scikit-learn==0.19.1
scipy==1.1.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.11.0
sklearn==0.0
spacy==2.0.11
strict-rfc3339==0.7
subprocess32==3.5.2
swagger-spec-validator==2.3.1
termcolor==1.1.0
thinc==6.10.2
toolz==0.9.0
tornado==5.0.2
tqdm==4.23.4
traitlets==4.3.2
ujson==1.35
urllib3==1.23
wcwidth==0.1.7
Werkzeug==0.14.1
Whoosh==2.7.4
wrapt==1.10.11```

**Comment by ashimko** [comment]
I have the same problem.

**Comment by HendrikStrobelt** [comment]
Sorry for the delay. I will look into it early next week (after vacation). Thanks for reporting !!

**Comment by kiariendegwa** [comment]
Getting the same error when using the same set up as @paulkarpenko. Thanks for maintaining this awesome repo.

**Comment by HendrikStrobelt** [comment]
Should work again. Thank you all for the feedback.
